Operator refresh
minio/docs-k8s pull request #8
Opened 2022-06-03 20:28 UTC by djwfyi

Closes #6 .

Updates the docs for the Operator GUI.

2022-06-06 22:32 UTC, ravindk89 requested changes
minor nits, excellent first pass. a few questions to follow up w/ engineering

2022-06-06 22:32 UTC, ravindk89 commented on source/tenant-management/deploy-minio-tenant-using-commandline.rst
> +Starting with v4.0.0, the MinIO Operator and MinIO Kubernetes Plugin require Kubernetes 1.19.0 and later.
v4 has been out a while now - i think we can safely state that we simply require K8s 1.19+.

2022-06-06 22:32 UTC, ravindk89 commented on source/tenant-management/deploy-minio-tenant-using-commandline.rst
> +The Operator generates one PVC for each volume in the tenant.
So I cannot find for the life of me where I wrote this down, but I distinctly remember at one point that you needed +2 volumes to account for logsearch (PostGRES) and Prometheus.

@Alevsk @dvaldivia does that sound right to you?

2022-06-06 22:32 UTC, ravindk89 commented on source/tenant-management/deploy-minio-tenant-using-commandline.rst
> +This procedure uses the MinIO :minio-git:`DirectCSI <direct-csi>` driver to automatically provision Persistent Volumes from locally attached drives to support the generated PVC.
This is now DirectPV - update all references to match.

2022-06-06 22:32 UTC, ravindk89 commented on source/tenant-management/deploy-minio-tenant.rst
> +Starting with v4.0.0, the MinIO Operator requires Kubernetes 1.19.0 or later.
Same note dropping the "Starting with" - we can even state |stable-minio-operator| requires... or whatever the sub-var is

2022-06-06 22:32 UTC, ravindk89 commented on source/tenant-management/deploy-minio-tenant.rst
>         requests per Server.
Aha - here is the +2 - if the `kubectl minio tenant create` command doesn't also create the logsearch + prometheus pods, then that extra factor might not be necessary.

Easy enough to check - see what the output of `kubectl tenant create <params> --output` is (that might not be the right param name anymore)

2022-06-06 22:32 UTC, ravindk89 commented on source/tenant-management/deploy-minio-tenant.rst
> +     - Specify the number of CPUs to reserve on each node.
OK so we should clarify, since users may not be aware, that Requests are "soft" and limits are "hard"

https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits

Arguably should be in the UI if it's not already.

2022-06-06 22:32 UTC, ravindk89 commented on source/tenant-management/deploy-minio-tenant.rst
> +   * - | :guilabel:`CPU Limit`
According to kube docs, setting this value but not setting a request value is the same as setting the request to the limit.

It's K8s behavior but maybe we should mention it here as well.

2022-06-06 22:32 UTC, ravindk89 commented on source/tenant-management/deploy-minio-tenant.rst
> +     - Specify the number of CPUs to reserve on each node.
Also what the behavior is if no request or is set (Pod can use up to the Limit or, if no limit, as much CPU as is available on the worker)

2022-06-06 22:32 UTC, ravindk89 commented on source/tenant-management/deploy-minio-tenant.rst
> +     - You can define custom domains to use to access the tenant and the tenant's
These domains have to be routable right? There has to be ingress, LB, or other network control plane component that knows requests for "mydata.minio.example.org" should go to this tenant.

2022-06-06 22:32 UTC, ravindk89 commented on source/tenant-management/deploy-minio-tenant.rst
> +       All three entries are required to access the private registry.
Passive, spitballing:

`Specify all three entries to configure custom registry access`

2022-06-06 22:32 UTC, ravindk89 commented on source/tenant-management/deploy-minio-tenant.rst
> +     - Set the toggle to :guilabel:`ON` to repel pods from running on the same node
i would not have thought to use 'repel' here. Feels like a physics lesson.

Just "prevent" should be fine? specifically prevents Kubernetes to never schedule more than one tenant pod per worker node.

2022-06-06 22:32 UTC, ravindk89 commented on source/tenant-management/deploy-minio-tenant.rst
> +       as another similar pod.
Begs the question to check if we are setting affinity for logsearch/prometheus pods, as those are not similar to MinIO server pods

2022-06-06 22:32 UTC, ravindk89 commented on source/tenant-management/deploy-minio-tenant.rst
> +       Use this option to choose whether to use the defined :guilabel:`Labels` for :kube-docs:`affinity or anti-affinity <concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity>`.
"Configure this option to direct Kubernetes to use the defined ..."

Scheduling is all about Kubernetes.

2022-06-06 22:32 UTC, ravindk89 commented on source/tenant-management/deploy-minio-tenant.rst
> +     - Add the label key:value pairs to use to define affinity or anti-affinity for pod placement.
Maybe add a graf: "The specified labels must allow MinIO to deploy all pods in the Tenant onto the Kubernetes infrastructure."

It's a little extra, but just reaffirms that users need to think about these labels.

2022-06-06 22:32 UTC, ravindk89 commented on source/tenant-management/deploy-minio-tenant.rst
> +     - Configure additional users for the Operator to create as part of deploying
I think you can compact this slightly by bringing the 'internal MinIO identity management" up. Spitballing:

"Configure additional MinIO-managed users..."

2022-06-07 14:57 UTC, djwfyi commented on source/tenant-management/deploy-minio-tenant-using-commandline.rst
> +Starting with v4.0.0, the MinIO Operator and MinIO Kubernetes Plugin require Kubernetes 1.19.0 and later.
👍

2022-06-07 14:59 UTC, djwfyi commented on source/tenant-management/deploy-minio-tenant-using-commandline.rst
> +The Operator generates one PVC for each volume in the tenant.
Updated this and the following line to reflect the two additional volume claims.

2022-06-07 15:08 UTC, djwfyi commented on source/tenant-management/deploy-minio-tenant-using-commandline.rst
> +This procedure uses the MinIO :minio-git:`DirectCSI <direct-csi>` driver to automatically provision Persistent Volumes from locally attached drives to support the generated PVC.
Updated throughout

2022-06-07 15:11 UTC, djwfyi commented on source/tenant-management/deploy-minio-tenant.rst
> +Starting with v4.0.0, the MinIO Operator requires Kubernetes 1.19.0 or later.
Changed and included the replacement variable

2023-01-26 21:44 UTC, closed without merging